<a href="https://colab.research.google.com/github/rtajeong/M3_new_2025/blob/main/M3_lab51_bag_of_word.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bag of Word (BOW)
- Document-Term Matrix and Tfidf Matrix

뉴스기사 분석
- 문서-단어 행렬의 예시 (Document-term Matrix)
- 빅카인즈 뉴스기사 데이터 활용(https://www.bigkinds.or.kr/): 한국언론진흥재단이 운영하는 사이트로
  국내 언론사들 뉴스기사의 분야별 키워드, 통계, 이슈 등을 제공한다.
- 여기서는 2019년 뉴스 데이터 사용

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
# 뉴스 데이터 가져오기
!curl -L https://bit.ly/2X7UON2 -o news.xlsx

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128  100   128    0     0    448      0 --:--:-- --:--:-- --:--:--   449
100   141  100   141    0     0    198      0 --:--:-- --:--:-- --:--:--     0
100    17  100    17    0     0     12      0  0:00:01  0:00:01 --:--:--    12
100   470    0   470    0     0    258      0 --:--:--  0:00:01 --:--:--  1620
100 1789k  100 1789k    0     0   847k      0  0:00:02  0:00:02 --:--:--  847k


In [3]:
# !dir

In [4]:
news_all = pd.read_excel("news.xlsx")
news_all.columns

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


Index(['뉴스 식별자', '일자', '언론사', '기고자', '제목', '통합 분류1', '통합 분류2', '통합 분류3',
       '사건/사고 분류1', '사건/사고 분류2', '사건/사고 분류3', '인물', '위치', '기관', '키워드', '특성추출',
       '본문', 'URL', '분석제외 여부'],
      dtype='object')

In [5]:
news_all.head(2)

뉴스 식별자        일자   언론사                        기고자  \
0  1.500401e+06  20190228  국제신문  김태경 기자 tgkim@kookje.co.kr   
1  1.200201e+06  20190228  경인일보                        조영상   

                                    제목   통합 분류1  통합 분류2 통합 분류3 사건/사고 분류1  \
0       빅딜이냐 스몰딜이냐 ‘영변 핵+α’ 로드맵 도출이 관건    정치>북한   정치>외교    NaN       NaN   
1  하노이 도착후 실무대표단 청취 김정은, 북미회담 성공 '잰걸음'  국제>국제일반   정치>북한    NaN       NaN   

  사건/사고 분류2 사건/사고 분류3                 인물                        위치  \
0       NaN       NaN  김,도널드 트럼프,김의겸,김정은  북미,미국,하노이,서울,싱가포르,북한,리비아   
1       NaN       NaN                  김                북미,하노이,베트남   

                                기관  \
0  북미,북미 정상회,미국,청와대,북미 정상회담,북한,국무위   
1                       조선중앙통신,국무위   

                                                 키워드  \
0  빅딜,스몰딜,영변,로드맵,도출,비핵화,수준,상응,조치,막판,양국,협상팀,밀당,1차,...   
1  하노이,도착,실무대표단,청취,김정은,잰걸음,북미회담,성공,김정은,국무,위원장,시작,...   

                                                특성추출  \
0  북미,비핵화,미국,스몰딜,1차,정상회담,김정은,종전선언,연락사무소,하노이,영변,대변...   
1  실무대표단,하노이,김정은,위원장,베트남,북미정상회담,북미회담,정상회담,조선중앙통신,...   

                                                  본문  \
0  - 비핵화 수준 상응 조치 놓고\n- 양국 협상팀 막판까지 ‘밀당’\n- 1차 때와...   
1  김정은 국무위원장이 27일 시작되는 제2차 북미정상회담 성공을 위해 심혈을 기울이고...   

                                                 URL 분석제외 여부  
0  http://www.kookje.co.kr/news2011/asp/newsbody....     NaN  
1  http://www.kyeongin.com/main/view.php?key=2019...     NaN

In [6]:
news_text = news_all['본문']
news_text[:5]

0    - 비핵화 수준 상응 조치 놓고\n- 양국 협상팀 막판까지 ‘밀당’\n- 1차 때와...
1    김정은 국무위원장이 27일 시작되는 제2차 북미정상회담 성공을 위해 심혈을 기울이고...
2    북미가 처음으로 정상 간 단독회담과 만찬을 가지며 또다시 새로운 역사 창조에 나섰다...
3    지난해 9월 남북정상회담 당시 리선권 북한 조국평화통일위원장의 '냉면' 발언으로 정...
4    지자체 민간 교류 활성화 대부분 \n여, 부처간 논의 예산 지원 확대 \n야, 사업...
Name: 본문, dtype: object

In [7]:
len(news_text[0])

200

In [8]:
type(news_text)

pandas.core.series.Series

In [9]:
cv = CountVectorizer()
dtm = cv.fit_transform(news_text)

In [10]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 60645 stored elements and shape (1543, 16199)>

In [11]:
dtm.toarray()  # dtm.A

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
dtm.toarray().shape

(1543, 16199)

In [13]:
cv.get_feature_names_out()

array(['00', '000원을', '001420', ..., '힘이', '힘입어', '靈山'], dtype=object)

In [15]:
dtm.shape

(1543, 16199)

In [16]:

df = pd.DataFrame(pd.DataFrame(dtm.toarray(), columns = cv.get_feature_names_out()))
df[:5]

00  000원을  001420  001550  002100  005690  01  017800  02  025860  ...  \
0   0      0       0       0       0       0   0       0   0       0  ...   
1   0      0       0       0       0       0   0       0   0       0  ...   
2   0      0       0       0       0       0   0       0   0       0  ...   
3   0      0       0       0       0       0   0       0   0       0  ...   
4   0      0       0       0       0       0   0       0   0       0  ...   

   힌국당  힘겨루기로  힘겨웠던  힘들다고  힘들어  힘들어지는  힘을  힘이  힘입어  靈山  
0    0      0     0     0    0      0   0   0    0   0  
1    0      0     0     0    0      0   0   0    0   0  
2    0      0     0     0    0      0   0   0    0   0  
3    0      0     0     0    0      0   0   0    0   0  
4    0      0     0     0    0      0   0   0    0   0  

[5 rows x 16199 columns]

In [17]:
df.shape    # 총 단어의 수가 16,199 개

(1543, 16199)

In [35]:
# 어떤 단어들이 등장했는지 확인 - dict
len(cv.vocabulary_.items()), type(cv.vocabulary_.items())

(200, dict_items)

In [20]:
# 문서-단어 행렬에서 가장 많이 등장하는 단어 찾기 (이것이 훨씬 간단)
df.sum()    # column-wise sum
pd.Series(df.sum()).idxmax(), pd.Series(df.sum()).max()

('2차', 980)

In [21]:
# DSAC 교재에 나타난 코드 (결과는 위와 동일)
top_word = []
for i in df.T.values:    # df.T.values 와 동일 (2-d array)
    top_word.append(sum(i.tolist()))

df.transpose().index[top_word.index(max(top_word))]

'2차'

In [22]:
# maximum 200 개만 사용하도록 하기 위해서는?
cv = CountVectorizer(max_features=200)
dtm = cv.fit_transform(news_text)
df = pd.DataFrame(pd.DataFrame(dtm.toarray(), columns = cv.get_feature_names_out()))
print(df.shape)
df[:6]

(1543, 200)


10일  11일  17일  18일  19일  1차  21일  24일  25일  26일  ...  함께  했다  헤럴드경제  현지시간  \
0    0    0    0    0    0   1    0    0    0    0  ...   0   0      0     0   
1    0    0    0    0    0   0    0    0    0    1  ...   0   0      0     0   
2    0    0    0    0    0   0    0    0    0    0  ...   0   0      0     1   
3    0    0    0    0    0   0    0    0    0    0  ...   0   0      0     0   
4    0    0    0    0    0   0    0    0    0    0  ...   0   0      0     0   
5    0    0    0    0    0   0    0    0    0    0  ...   0   0      0     0   

   협상  협상을  홍영표  회담  회담을  회담이  
0   0    0    0   1    0    0  
1   0    0    0   0    0    0  
2   0    0    0   0    0    0  
3   0    0    0   0    0    0  
4   0    0    0   0    0    0  
5   0    0    0   0    0    0  

[6 rows x 200 columns]

In [23]:
df.max(axis=1)

0       2
1       2
2       1
3       1
4       1
       ..
1538    2
1539    2
1540    1
1541    2
1542    2
Length: 1543, dtype: int64

In [24]:
tv = TfidfVectorizer(max_features=200)
dtm = tv.fit_transform(news_text.values)
df = pd.DataFrame(pd.DataFrame(dtm.toarray(), columns = tv.get_feature_names_out()))
print(df.shape)
df[:6]

(1543, 200)


10일  11일  17일  18일  19일        1차  21일  24일  25일       26일  ...   함께   했다  \
0  0.0  0.0  0.0  0.0  0.0  0.346577  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.258984  ...  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
5  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.000000  ...  0.0  0.0   

   헤럴드경제      현지시간   협상  협상을  홍영표        회담  회담을  회담이  
0    0.0  0.000000  0.0  0.0  0.0  0.287727  0.0  0.0  
1    0.0  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  
2    0.0  0.274912  0.0  0.0  0.0  0.000000  0.0  0.0  
3    0.0  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  
4    0.0  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  
5    0.0  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  

[6 rows x 200 columns]

# 연습

In [25]:
df2 = pd.DataFrame(np.arange(12).reshape(3,4)); df2
df2.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
df2.sum()

0    12
1    15
2    18
3    21
dtype: int64

In [27]:
df2.max()

0     8
1     9
2    10
3    11
dtype: int64

In [28]:
df2.idxmax(axis=1)

0    3
1    3
2    3
dtype: int64

In [29]:
df2.T.idxmax()

0    3
1    3
2    3
dtype: int64

In [30]:
for i in df2.values:
    print(sum(i))

6
22
38


In [31]:
tmp=[]
for i in df2.T.values:
    tmp.append(sum(i))

In [32]:
tmp

[np.int64(12), np.int64(15), np.int64(18), np.int64(21)]

In [33]:
tmp=np.array(df2.sum()); tmp

array([12, 15, 18, 21])

In [34]:
tmp_s = pd.Series(tmp)
tmp_s.idxmax()

3